# Spring
spring:
  profiles:
    active: native
  application:
    name: config-server

## Server
server:
  port: 8888

## Info
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

# Logging
logging:
  path: log/
  level.root: warn


# Management
management:
  info:
     git:
       mode: full
  health:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
